app = "tipinj"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[env]
  INJECTIVE_NETWORK = "testnet"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[deploy]
  strategy = "immediate"

[[mounts]]
  source = "tipbot_data"
  destination = "/data"
